<?php

/**
 * ActividadProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ActividadProductoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return ActividadTableTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ActividadProducto');
    }

    public function findAllByProductId($id, $mes, $year) {
        if (!$year || $year === '%') {
            $year = date("Y");
        }
        if (!$mes || $mes === '%') {
            $mes = date("m");
        }
        $temp = $year . '-' . $mes . '%';
        return $this->createQuery('actividad_producto')
                        ->select('actividad_producto.*,act.*,pro.*,pro.nombre as producto_nombre')
                        ->innerJoin('actividad_producto.Actividad act')
                        ->innerJoin('actividad_producto.Producto pro')
                        ->where('pro.id = ?', $id)
                        ->andWhere('actividad_producto.fecha like "' . $temp . '"')
                        ->orderBy('act.nombre')
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
    }

    public function findAllByProduct($mes, $year) {
        if (!$year || $year === '%') {
            $year = date("Y");
        }
        if (!$mes || $mes === '%') {
            $mes = date("m");
        }
        $temp = $year . '-' . $mes . '%';
        return $this->createQuery('actividad_producto')
                        ->select('actividad_producto.*,act.*,(actividad_producto.actual*100)/actividad_producto.plan as porciento,pro.*,pro.nombre as producto_nombre')
                        ->innerJoin('actividad_producto.Actividad act')
                        ->innerJoin('actividad_producto.Producto pro')
                        ->andWhere('actividad_producto.fecha like "' . $temp . '"')
                        ->orderBy('act.nombre')
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
    }

    public function productos($time) {
        return $this->createQuery('actividad_producto')
                        ->select('actividad_producto.*,pro.*,pro.nombre as producto_nombre,um.nombre as unidad_medida')
                        ->innerJoin('actividad_producto.Producto pro')
                        ->innerJoin('pro.Um um')
                        ->andWhere('actividad_producto.fecha like "' . $time . '"')
                        ->groupBy('producto_nombre')
                        ->orderBy('producto_nombre')
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
    }

    public function productos_por_meses($mes, $year) {
        $time = $year . '-' . $mes . '%';
        return $this->createQuery('actividad_producto')
                        ->select('actividad_producto.*,act.*,act.nombre as actividad_nombre,(actividad_producto.actual*100)/actividad_producto.plan as porciento,pro.*,pro.nombre as producto_nombre')
                        ->innerJoin('actividad_producto.Actividad act')
                        ->innerJoin('actividad_producto.Producto pro')
                        ->andWhere('actividad_producto.fecha like "' . $time . '"')
                        ->orderBy('act.nombre')
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
    }

    public function matrix($actividades, $productos, $array_actividad_producto) {
        $arr = array();
        foreach ($productos as $value) {
            $arr2 = array();
            foreach ($actividades as $value2) {
                $arr2[$value2['nombre']] = array('plan' => 0, 'actual' => 0, 'porciento' => 0);
            }
            $arr[$value['producto_nombre']] = $arr2;
        }
        foreach ($array_actividad_producto as $value) {
            $arr[$value['producto_nombre']][$value['actividad_nombre']]['plan'] = $value['plan'];
            $arr[$value['producto_nombre']][$value['actividad_nombre']]['actual'] = $value['actual'];
            $arr[$value['producto_nombre']][$value['actividad_nombre']]['porciento'] = $value['porciento'];
        }
        return $arr;
    }

}
