<?php

/**
 * BoletaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AppaRoleTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return BoletaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('AppaRole');
    }

    public function getRole($user_id) {
        $query = Doctrine_Query::create()->select('role.name nombre')
                ->from('AppaRole role')
                ->innerJoin('role.AppaUserRole userRole')
                ->where('userRole.user_id = ?', $user_id)
                ->orderBy('role.id asc LIMIT 0, 1');
        $arr = $query->execute()->toArray(true);
        if ($arr)
            return $arr[0]['nombre'];
        else
            return null;
    }

}
