<?php

/**
 * NomProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AppaUserLoginAttemptTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return BalanceAlimTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('AppaUserLoginAttempt');
    }

    private function _getPreparedQuery($start, $limit) {
        return $this->createQuery('appa_user_login_attempt')
                        ->select('appa_user_login_attempt.*')
                        ->orderBy('appa_user_login_attempt.id ' . " LIMIT " . $start . ", " . $limit)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
    }

    public function registros($start, $limit) {
        return $this->_getPreparedQuery($start, $limit)->execute();
    }

}
