<?php

/**
 * BalanceMesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BalanceMesTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return BalanceMesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('BalanceMes');
    }

    public function getStore($balance_alim_id, $mes, $year) {
    	if ($year === '%') {
            $year = date("Y");
        }
        if ($mes === '%') {
            $mes = date("m");
        }
        $time = $year . '-' . $mes . '%';
        return $this->createQuery('balance_mes')
                        ->innerJoin('balance_mes.BalanceAlim ba')
                        ->where('balance_mes.balance_id = ?', $balance_alim_id)
                        ->andWhere('balance_mes.created_at like ?',$time)
                        ->fetchArray();
    }

}
