<?php

/**
 * BoletaProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##Norbyn## <##norbyn.leyva@gmail.com##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BoletaProductoTable extends Doctrine_Table {

    public static function getInstance() {
        return Doctrine_Core::getTable('BoletaProducto');
    }

    public function findBoletaProducto() {
        return $this->createQuery('boleta_producto')
                        ->innerJoin('boleta_producto.Producto pro')
                        ->innerJoin('boleta_producto.Boleta b')
                        ->orderBy('boleta_producto.id')
                        ->fetchArray();
    }

    public function findByEntidad_Id($id) {
        $temp = date("Y-m") . '%';
        return $this->createQuery('boleta_producto')
                        ->select('boleta_producto.*,ent.*,pro.*, pro.nombre as producto_nombre')
                        ->innerJoin('boleta_producto.Entidad ent')
                        ->innerJoin('boleta_producto.Producto pro')
                        ->where('ent.id = ?', $id)
                        ->andWhere('boleta_producto.fecha like "' . $temp . '"')
                        ->fetchArray();
    }

    public function findByProveedor_Id($id, $mes, $year) {
        if ($year === '%') {
            $year = date("Y");
        }
        if ($mes === '%') {
            $mes = date("m");
        }
        $temp = $year . '-' . $mes . '%';
        return $this->createQuery('boleta_producto')
                        ->select('boleta_producto.*,ent.*,pro.*, pro.nombre as producto_nombre,ent.nombre as entidad_nombre')
                        ->innerJoin('boleta_producto.Entidad ent')
                        ->innerJoin('boleta_producto.Producto pro')
                        ->innerJoin('pro.Proveedor prov')
                        ->where('prov.id like "' . $id . '"')
                        ->andWhere('boleta_producto.fecha like "' . $temp . '"')
                        ->orderBy('boleta_producto.consec')
                        ->fetchArray();
    }

    public function findAllByEntidadId($id) {
        return $this->createQuery('boleta_producto')
                        ->innerJoin('boleta_producto.Entidad ent')
                        ->where('boleta_producto.entidad_id = ?', $id)
                        ->fetchArray();
    }

    public function getStore($boleta_id) {
        return $this->createQuery('boleta_producto')
                        ->innerJoin('boleta_producto.Producto pro')
                        ->innerJoin('boleta_producto.Boleta bo')
                        ->where('boleta_producto.boleta_id = ?', $boleta_id)
                        ->fetchArray();
    }

}
