<?php

/**
 * NomProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ComedorTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return ComedorTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Comedor');
    }

    /**
     * Encuentra el listado de comedores dado el id de una Entidad
     * 
     * @param int $id
     * @return array
     */
    public function findByEntidadId($id) {
        $time = date("Y") . '%';
        $q = $this->createQuery('comedor')
                ->select('comedor.*, tipo.nombre as nombre, tipo.is_evento as is_evento')
                ->innerJoin('comedor.TipoComedor tipo')
                ->where('comedor.entidad_id = ?', $id)
                ->andWhere('comedor.id not in (select comedor_id from balance_alim where created_at like ?)', $time)
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
        return $q->execute();
    }

    public function findWithComedorEntidad() {
        return $this->createQuery('comedor')
                        ->select('comedor.*, ent.nombre as entidad_nombre, com.nombre as nombre')
                        ->innerJoin('comedor.Entidad ent')
                        ->innerJoin('comedor.TipoComedor com')
                        ->orderBy('nombre')
                        ->fetchArray();
    }

    public function findAllByEntidadId($id) {
        return $this->createQuery('comedor')
                        ->innerJoin('comedor.Entidad ent')
                        ->innerJoin('comedor.TipoComedor com')
                        ->where('comedor.entidad_id = ?', $id)
                        ->fetchArray();
    }

}
