<?php

/**
 * DisponibilidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DisponibilidadTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return DisponibilidadTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Disponibilidad');
    }

    private function _getPreparedQuery($mes, $year) {
        if (!$year || $year === '%') {
            $year = date("Y");
        }
        if (!$mes || $mes === '%') {
            $mes = date("m");
        }
        $temp = $year . '-' . $mes . '%';
        return $this->createQuery('disponibilidad')
                        ->select('disponibilidad.*,um.nombre as um, prod.nombre as producto_nombre, prov.nombre as proveedor_nombre')
                        ->innerJoin('disponibilidad.Producto prod')
                        ->innerJoin('prod.Um um')
                        ->innerJoin('prod.Proveedor prov')
                        ->where('disponibilidad.fecha like "' . $temp . '"')
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
    }

    public function findAllWithProduct($mes, $year) {
        return $this->_getPreparedQuery($mes, $year)->execute();
    }

}
