<?php

/**
 * Inventario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class InventarioTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return InventarioTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Inventario');
    }

    /** Devuelve todos los inventarios
     * 
     * @return type
     */
    public function findAllWithEntidadProducto($mes, $year) {
        if (!$year || $year === '%') {
            $year = date("Y");
        }
        if (!$mes || $mes === '%') {
            $mes = date("m");
        }
        $temp = $year . '-' . $mes . '%';
        return $this->createQuery('inventario')
                        ->select('inventario.*, pro.nombre as producto_nombre'
                                . ',ent.nombre as entidad_nombre,prov.nombre as proveedor')
                        ->innerJoin('inventario.Producto pro')
                        ->innerJoin('pro.Proveedor prov')
                        ->innerJoin('inventario.Entidad ent')
                        ->where('inventario.fecha like "' . $temp . '"')
                        ->orderBy('producto_nombre')
                        ->fetchArray();
    }

    public function findByEntidadId($id, $mes, $year) {
        if (!$year || $year === '%') {
            $year = date("Y");
        }
        if (!$mes || $mes === '%') {
            $mes = date("m");
        }
        $temp = $year . '-' . $mes . '%';
        return $this->createQuery('inventario')
                        ->select('inventario.*,ent.*,pro.*, pro.nombre as producto_nombre')
                        ->innerJoin('inventario.Entidad ent')
                        ->innerJoin('inventario.Producto pro')
                        ->where('ent.id = ?', $id)
                        ->andWhere('inventario.fecha like "' . $temp . '"')
                        ->fetchArray();
    }

}
