<?php

/**
 * NomComedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NomComedorTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return NomComedorTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('NomComedor');
    }

}
