<?php

/**
 * NomFuentesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NomFuentesTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return NomFuentesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('NomFuentes');
    }

    public function fuentes($time) {
        return Doctrine_Query::create()->select('fuentes.id as fuente_id, fuentes.nombre, pf.fecha')
                        ->from('NomFuentes fuentes')
                        ->innerJoin('fuentes.ProductoFuentes pf')
                        ->where('pf.fecha like "' . $time . '"')
                        ->orderBy('fuentes.id')->execute()->toArray(true);
    }

}
