<?php

/**
 * NomMercadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NomMercadoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return NomMercadoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('NomMercado');
    }

    public function mercados($time) {
        return Doctrine_Query::create()->select('mercado.id as mercado_id, mercado.nombre, pm.fecha')
                        ->from('NomMercado mercado')
                        ->innerJoin('mercado.ProductoMercado pm')
                        ->where('pm.fecha like "' . $time . '"')
                        ->orderBy('mercado.id')->execute()->toArray(true);
    }

}
