<?php

/**
 * NomProveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NomProveedorTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return NomProveedorTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('NomProveedor');
    }

    private function _getPreparedQuery($start, $limit) {
        return $this->createQuery('nom_proveedor')
                        ->select('nom_proveedor.*')
                        ->orderBy('nom_proveedor.id ' . " LIMIT " . $start . ", " . $limit)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
    }

    public function proveedores($start, $limit) {
        return $this->_getPreparedQuery($start, $limit)->execute();
    }

}
