<?php

/**
 * ProductoMercadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductoMercadoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return ProductoMercadoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ProductoMercado');
    }

    public function findAllWithProductoMercado($start, $limit, $mes, $year) {
        if (!$year || $year === '%') {
            $year = date("Y");
        }
        $mes = '%';
        $time = $year . '-' . $mes . '%';
        return $this->createQuery('producto_mercado')
                        ->innerJoin('producto_mercado.Producto pro')
                        ->innerJoin('pro.Proveedor prov')
                        ->innerJoin('producto_mercado.Mercado mercado')
                        ->where('producto_mercado.fecha like "' . $time . '"')
                        ->orderBy('prov.id, producto_mercado.id ' . " LIMIT " . $start . ", " . $limit)
                        ->fetchArray();
    }

    public function cantidad($time, $producto_id, $mercado_id) {
        return Doctrine_Query::create()->select('pm.cant as cantidad')
                        ->from('ProductoMercado pm')
                        ->where('pm.fecha like "' . $time . '"')
                        ->andWhere('pm.producto_id = ?', $producto_id)
                        ->andWhere('pm.mercado_id = ?', $mercado_id)
                        ->execute()->toArray(true);
    }

}
